<?php
$title = 'Delete group';
$this->headTitle($title);

?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($group['type']); ?>' -
    '<?php echo $this->escapeHtml($group['name']); ?>'?
</p>
<?php
$url = $this->url('admin-group', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $group['id']; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>