<?php include '_adminHeader.phtml'; ?>
<?php 
$form->prepare();
$form->setAttribute('action', $url . '/admin/delete');
$form->setAttribute('method', 'post');
echo $this->form()->openTag($form);
?>
<h3>Users to Delete</h3>
<table>
<tr><td>
<?php 
    $users = $form->get('users');
    $this->formMultiCheckbox()->setSeparator('</td></tr><tr><td>');
    echo $this->formMultiCheckbox($users);
    echo $this->formElementErrors($users);
?>
</td></tr>
</table>
<p>&nbsp;</p>
<div class="form_element_submit">
<?php 
    $submit = $form->get('submit');
    echo $this->formElement($submit);
?>
<?php 
echo $this->form()->closeTag($form);
?>
<hr />
<?php echo $message; ?>
<br />Form Data Submitted:
<pre>
<?php $this->escapeHtml(var_dump($data)); ?>
</pre>
</p>
